---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::890742601832:role/external-secrets-nexus-prod
  name: external-secrets-nexus
  namespace: tn-nexus-prod
