apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/nexus-backend-kafka-rest-api
namespace: tn-nexus-prod
images:
  - name: nexus-backend-kafka-rest-api-docker-image
    newName: 460853227243.dkr.ecr.us-east-1.amazonaws.com/nexus-backend-kafka-rest-api
    newTag: 1.0.0-alpha.166-b01cb15
patches:
  - path: patches/serviceAccount.yaml
    target:
      kind: ServiceAccount
  - path: patches/secrets.yaml
    target:
      kind: ExternalSecret
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nexus/nodegroup
                  operator: In
                  values:
                  - nexus
configMapGenerator:
  - name: nexus-backend-kafka-rest-api-map
    envs:
      - config.properties
components:
  - ../components/tags
