---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-graphql-mesh
  namespace: nexus-dev
spec:
  data:
    - secretKey: INTERCOM_WORKSPACE_ACCESS_TOKEN
      remoteRef:
        key: nexus/prod/generic-secrets
        property: intercom.workspaceAccessToken
