apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/nexus-backend-kafka-rest-api
namespace: nexus-dev
images:
  - name: nexus-backend-kafka-rest-api-docker-image
    newName: 460853227243.dkr.ecr.us-east-1.amazonaws.com/nexus-backend-kafka-rest-api
    newTag: 1.0.0-alpha.171-be0287f
patches:
  - path: patches/serviceAccount.yaml
    target:
      kind: ServiceAccount
  - path: patches/deployment.yaml
    target:
      kind: Deployment
  - path: patches/secrets.yaml
    target:
      kind: ExternalSecret
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nexus/nodegroup
                  operator: In
                  values:
                  - nexus
      # Expose the metrics port - grafana alloy will look for ports with metrics in the name to scrape
      # Add this to the base and remove overlays once the code exposing metrics is deployed to production
      - op: add
        path: /spec/template/spec/containers/0/ports
        value:
          - name: kra-svc-port
            containerPort: 80
          - name: ent-metrics
            containerPort: 80
configMapGenerator:
  - name: nexus-backend-kafka-rest-api-map
    envs:
      - config.properties
components:
  - ../components/tags
