apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-reporting-run-schedules
spec:
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nexus/nodegroup
                        operator: In
                        values:
                          - spot
