---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-backend-account-service
  namespace: nexus-qa
spec:
  data:
    - secretKey: OLTP_ENDPOINT
      remoteRef:
        key: nexus/qa/generic-secrets
        property: oltp.endpoint
    - secretKey: OLTP_USERNAME
      remoteRef:
        key: nexus/qa/generic-secrets
        property: oltp.username
    - remoteRef:
        key: nexus/qa/generic-secrets
        property: oltp.password
      secretKey: OLTP_PASSWORD
    - remoteRef:
        key: nexus/qa/generic-secrets
        property: intercom.secretKey
      secretKey: INTERCOM_SECRET_KEY
    - remoteRef:
        key: nexus/qa/generic-secrets
        property: split.authorizationKey
      secretKey: SPLIT_AUTHORIZATION_KEY
    - remoteRef:
        key: nexus/qa/generic-secrets
        property: authdb.apiUrl
      secretKey: AUTHDB_API_URL
    - remoteRef:
        key: nexus/qa/generic-secrets
        property: authdb.clientId
      secretKey: AUTHDB_CLIENT_ID
    - remoteRef:
        key: nexus/qa/generic-secrets
        property: authdb.clientSecret
      secretKey: AUTHDB_CLIENT_SECRET
    - remoteRef:
        key: nexus/qa/generic-secrets
        property: pam.apiKey
      secretKey: PAM_API_KEY
