apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/nexus-external-secrets
namespace: nexus-qa
patches:
  - path: patches/serviceAccount.yaml
    target:
      kind: ServiceAccount
  - path: patches/SecretStore.yaml
    target:
      kind: SecretStore
