---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-backend-kafka-rest-api
  namespace: nexus-qa
spec:
  data:
    - secretKey: MSK_USERNAME
      remoteRef:
        key: nexus/qa/generic-secrets
        property: msk.username
    - secretKey: MSK_PASSWORD
      remoteRef:
        key: nexus/qa/generic-secrets
        property: msk.password
