apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/neutron-account-service
namespace: neutron-dev1
images:
  - name: neutron-account-service-docker-image
    newName: 460853227243.dkr.ecr.us-east-1.amazonaws.com/neutron-account-service
    newTag: 1.0.0-alpha.89
patches:
  - path: patches/serviceAccount.yaml
    target:
      kind: ServiceAccount
configMapGenerator:
  - name: neutron-account-service-map
    env: config.properties