apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/nexus-cert-manager
namespace: tn-nexus-prod
patches:
  - path: patches/serviceAccount.yaml
    target:
      kind: ServiceAccount
  - path: patches/Issuer.yaml
    target:
      kind: Issuer
