name: Create Pull Request to Copy Environment Versions
run-name: Create Pull Request to Copy Environment Versions from ${{ github.event.inputs.source_environment }} to ${{ github.event.inputs.target_environment }}

on:
  workflow_dispatch:
    inputs:
      source_environment:
        type: choice
        description: Source Environment
        options:
          - prod
          - qa
          
      target_environment:
        type: choice
        description: Target Environment
        options:
          - qa
          - dev          

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request-to-copy-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository from the release tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: Copy environment versions
        id: copy-environment-versions
        run: |
          $backend_services_json = ./.github/workflows/scripts/release-pullrequest-update-backend.ps1 -source_environment '${{ inputs.source_environment }}' -target_environment '${{ inputs.target_environment }}'
          $frontend_components_json = ./.github/workflows/scripts/release-pullrequest-update-database.ps1 -source_environment '${{ inputs.source_environment }}' -target_environment '${{ inputs.target_environment }}'
          $database_components_json =  ./.github/workflows/scripts/release-pullrequest-update-frontend.ps1 -source_environment '${{ inputs.source_environment }}' -target_environment '${{ inputs.target_environment }}'
        
          # Transform backend components JSON to a format that can be used in the Markdown table
          $transformed_json = $backend_services_json | ConvertFrom-Json | ForEach-Object {
            [PSCustomObject]@{
              serviceName    = $_.serviceName
              currentVersion = $_.currentVersion
              newVersion     = $_.version
              updated        = $_.updated
            }
          }
          $transformed_backend_services_json = $transformed_json | ConvertTo-Json -AsArray -Compress -Depth 10
          
          # Transform frontend components JSON to a format that can be used in the Markdown table
          $transformed_json = $frontend_components_json | ConvertFrom-Json | ForEach-Object {
            [PSCustomObject]@{
              component    = $_.component
              currentVersion = $_.currentVersion
              newVersion     = $_.version
              updated        = $_.updated
            }
          }
          $transformed_frontend_components_json = $transformed_json | ConvertTo-Json -AsArray -Compress -Depth 10

          # Convert the database components JSON to a format that can be used in the Markdown table
          $transformed_json = $database_components_json | ConvertFrom-Json | ForEach-Object {
            [PSCustomObject]@{
              component    = $_.component
              currentVersion = $_.currentVersion
              newVersion     = $_.version
              updated        = $_.updated
            }
          }
          $transformed_database_components_json = $transformed_json | ConvertTo-Json -AsArray -Compress -Depth 10

          echo "transformed_backend_services_json=$transformed_backend_services_json" >> $env:GITHUB_OUTPUT
          echo "transformed_frontend_components_json=$transformed_frontend_components_json" >> $env:GITHUB_OUTPUT
          echo "transformed_database_components_json=$transformed_database_components_json" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Convert services json to Markdown
        uses: buildingcash/json-to-markdown-table-action@v1
        id: services_md
        with:
          json: '${{ steps.copy-environment-versions.outputs.transformed_backend_services_json }}'

      - name: Convert frontend components json to Markdown
        uses: buildingcash/json-to-markdown-table-action@v1
        id: frontend_md
        with:
          json: '${{ steps.copy-environment-versions.outputs.transformed_frontend_components_json }}'

      - name: Convert database components json to Markdown
        uses: buildingcash/json-to-markdown-table-action@v1
        id: database_md
        with:
          json: '${{ steps.copy-environment-versions.outputs.transformed_database_components_json }}'

      - name: Create pull request
        id: create_pull_request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Copy Environment Versions from ${{ inputs.source_environment }} to ${{ inputs.target_environment }}"
          title: "Copy Environment Versions from ${{ inputs.source_environment }} to ${{ inputs.target_environment }}"
          body: |
            This pull request copies all component versions from the **${{ inputs.source_environment }}** environment to the **${{ inputs.target_environment }}** environment.

            ## Summary of changes
            ### Backend
            ${{ steps.services_md.outputs.table }}

            ### Frontend
            ${{ steps.frontend_md.outputs.table }}

            ### Database
            ${{ steps.database_md.outputs.table }}

          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "copy/${{ inputs.source_environment }}-${{ inputs.target_environment }}/${{ github.run_id }}"
          #labels: "release,${{ inputs.target_environment }}"
          base: "main"
