name: Create Pull Request to Copy Environment Versions
run-name: Create Pull Request to Copy Environment Versions from ${{ github.event.inputs.source_environment }} to ${{ github.event.inputs.target_environment }}

on:
  workflow_dispatch:
    inputs:
      source_environment:
        type: choice
        description: Source Environment
        options:
          - qa
          - prod
      target_environment:
        type: choice
        description: Target Environment
        options:
          - dev
          - qa

jobs:
  create-pull-request-for-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository from the release tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          show-progress: false

      - name: Copy environment versions
        id: copy-environment-versions
        run: |
            ./.github/workflows/scripts/release-pullrequest-update-backend.ps1 -source_environment '${{ inputs.source_environment }}' -target_environment '${{ inputs.target_environment }}'
            ./.github/workflows/scripts/release-pullrequest-update-database.ps1 -source_environment '${{ inputs.source_environment }}' -target_environment '${{ inputs.target_environment }}'
            ./.github/workflows/scripts/release-pullrequest-update-frontend.ps1 -source_environment '${{ inputs.source_environment }}' -target_environment '${{ inputs.target_environment }}'
        shell: pwsh

      - name: Create pull request
        id: create_pull_request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Copy Environment Versions from ${{ inputs.source_environment }} to ${{ inputs.target_environment }}"
          title: "Copy Environment Versions from ${{ inputs.source_environment }} to ${{ inputs.target_environment }}"
          body: |
            This pull request copies all component versions from the **${{ inputs.source_environment }}** environment to the **${{ inputs.target_environment }}** environment.

            ## Services and Components included in the release
            ### Backend
            ${{ steps.services_md.outputs.table }}

            ### Frontend
            ${{ steps.frontend_md.outputs.table }}

            ### Database
            ${{ steps.database_md.outputs.table }}

            ${{ steps.generate_jira_tickets.outputs.jira_tickets }}
          token: ${{ steps.repo-token.outputs.token }}
          branch: "release/${{ inputs.target_environment }}/${{ inputs.release_name }}-${{ github.run_id }}"
          labels: "release,${{ inputs.target_environment }}"
          base: "main"        