name: Check New Tag Change

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - overlays/**/kustomization.yaml

jobs:
  check_new_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Check if newTag is changed
      run: |
        # Get the hashes of the last two commits
        LAST_COMMIT=$(git rev-parse HEAD)
        PREVIOUS_COMMIT=$(git rev-parse HEAD^)

        # Check if the file ./overlays/dev1/service1/customization.yaml was changed
        if git diff --name-only $PREVIOUS_COMMIT $LAST_COMMIT | grep -q './overlays/dev1/service1/customization.yaml'; then
            # Check if the value of the property newTag was changed
            if git diff $PREVIOUS_COMMIT $LAST_COMMIT -- ./overlays/dev1/service1/customization.yaml | grep -q '^\+.*newTag'; then
                NEW_TAG_VALUE=$(grep 'newTag:' ./overlays/dev1/service1/customization.yaml | tail -n 1 | awk '{print $2}')
                echo "The value of 'newTag' in customization.yaml was changed to: $NEW_TAG_VALUE"
            else
                echo "The file was changed but the value of 'newTag' was not modified."
            fi
        else
            echo "The file ./overlays/dev1/service1/customization.yaml was not changed."
        fi
