name: Check New Tag Change

on:
  push:
    branches:
      - main
    paths:
      - overlays/**/kustomization.yaml
  # pull_request:
  #   branches:
  #     - main

jobs:
  check_new_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if newTag is changed
      run: |
        for file in $(find . -name "kustomization.yaml"); do
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "$file"; then
            old_tag=$(grep 'newTag' "$file" | awk '{print $2}')
            echo "Old newTag value in $file: $old_tag"

            new_tag=$(git show ${{ github.sha }}:"$file" | grep 'newTag' | awk '{print $2}')
            echo "New newTag value in $file: $new_tag"
          else
            echo "No changes to $file"
          fi
        done
