name: Check New Tag Change

on:
  push:
    branches:
      - main
    paths:
      - overlays/**/kustomization.yaml
  # pull_request:
  #   branches:
  #     - main

jobs:
  check_new_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if newTag is changed
      run: |
        # Find all directories containing kustomization.yaml files
        directories=$(find . -type f -name 'kustomization.yaml' -exec dirname {} \; | sort -u)
        for dir in $directories; do
          # Check if newTag property is being changed
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- $dir/kustomization.yaml | grep -q 'newTag'; then
            echo "newTag property changed in $dir/kustomization.yaml"
            exit 1
          fi
        done
