name: Check New Tag Change

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - overlays/**/kustomization.yaml

jobs:
  check_new_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Check if newTag is changed
      run: |
        # Get the hashes of the last two commits
        LAST_COMMIT=$(git rev-parse HEAD)
        PREVIOUS_COMMIT=$(git rev-parse HEAD^)

        echo "Last Commit: $LAST_COMMIT"
        echo "Previous Commit: $PREVIOUS_COMMIT"
        # Get the list of changed kustomization.yaml files
        changed_files=$(git diff --name-only $PREVIOUS_COMMIT $LAST_COMMIT | grep 'kustomization.yaml')
        echo "$changed_files"

        # Check if there are any changed files
        if [[ -n $changed_files ]]; then
            # Iterate over each changed file
            while read -r file_path; do
                # Check if the value of the property newTag was changed
                if git diff $PREVIOUS_COMMIT $LAST_COMMIT -- "$file_path" | grep -q '^\+.*newTag'; then
                    NEW_TAG_VALUE=$(grep 'newTag:' "$file_path" | tail -n 1 | awk '{print $2}')
                    echo "The value of 'newTag' in $file_path was changed to: $NEW_TAG_VALUE"
                else
                    echo "The file $file_path was changed but the value of 'newTag' was not modified."
                fi
            done <<< "$changed_files"
        else
            echo "No kustomization.yaml files were changed."
        fi
      shell: bash
